### ISSUE TITLE
Github actions failure due to missing VK_KHR_external_memory_fd Vulkan extension

### ISSUE THREAD

**Issue by S-Dafarra** [ami-iit/yarp-device-openxrheadset#23]
In https://github.com/ami-iit/yarp-device-openxrheadset/actions/runs/2923665308 the tests failed with the error
```
Test project /home/runner/work/yarp-device-openxrheadset/yarp-device-openxrheadset/build
    Start 1: openxrheadset_test
1/1 Test #1: openxrheadset_test ...............***Failed    0.35 sec
Warning:  |yarp.device.openxrheadset| Runtime does not support the HTC Vive Trackers!
 INFO [p_create_system] Creating system:
	Builders:
		rgb_tracking: RGB tracking based devices (PSVR, PSMV, ...)
		lighthouse: Lighthouse-tracked (Vive, Index, Tundra trackers, etc.) devices builder
		remote: Remote simulation devices builder
		legacy: Legacy probing system
	No builder selected in config (or wasn't compiled in)
	No builder was certain that it could create a head device
	Selected legacy because it maybe could create a head
	Using builder legacy: Legacy probing system
	Result: XRT_SUCCESS
DEBUG [xrt_gfx_provider_create_system] Doing init 0x560397b2f200
ERROR [create_device] vk_create_device: VK_ERROR_EXTENSION_NOT_PRESENT
	Failed to create Vulkan device.
ERROR [xrt_gfx_provider_create_system] Failed to init compositor 0x[56](https://github.com/ami-iit/yarp-device-openxrheadset/runs/8007913672?check_suite_focus=true#step:13:57)0397b2f200
XR_ERROR_INITIALIZATION_FAILED in xrCreateInstance: Failed to create the system '-3'
Error [GENERAL | xrCreateInstance | OpenXR-Loader] : LoaderInstance::CreateInstance chained CreateInstance call failed
Error [GENERAL | xrCreateInstance | OpenXR-Loader] : xrCreateInstance failed
Error:  |yarp.device.openxrheadset| Failed to create XR instance.
Error:  Failed to initialize OpenXr interface.
[INFO] |yarp.device.openxrheadset| Closed
```

I checked the available Vulkan extensions and I noticed that the extension ``VK_KHR_external_memory_fd`` was present in https://github.com/ami-iit/yarp-device-openxrheadset/runs/7986680925?check_suite_focus=true, but it got removed in https://github.com/ami-iit/yarp-device-openxrheadset/runs/8007913672?check_suite_focus=true

This extension is required by ``monado``: https://gitlab.freedesktop.org/monado/monado/-/blob/06ee685e9a20e7e7a875f0ed4849b948aea4c575/src/xrt/compositor/main/comp_compositor.c#L595

**Comment by traversaro** [comment]
This is strange, did the lavapipe/mesa version in the base image changed?

**Comment by traversaro** [comment]
Indeed, the working version is installing mesa 22.2~git2206220600 from oibaf, while the broken version is installing mesa 21.2.6 from the regular ubuntu repos. Probably something is going wrong with oibaf? Anyhow, ubuntu 22.04 has mesa 22.0.5, perhaps that is enough without using oibaf repositories?

**Comment by traversaro** [comment]
I saw that an updated mesa was uploaded in oibaf 4 hours ago: https://launchpad.net/~oibaf/+archive/ubuntu/graphics-drivers . Perhaps we just had an hiccup in which the server already removed the old mesa without uploading the new one?

**Comment by S-Dafarra** [comment]
Thanks a lot @traversaro for the analysis. I tried running the Action again (https://github.com/ami-iit/yarp-device-openxrheadset/runs/8013744950?check_suite_focus=true) but it failed :thinking:

**Comment by traversaro** [comment]
By looking a bit more, it seems that oibaf removed almost all the packages for Focal (see https://launchpad.net/~oibaf/+archive/ubuntu/graphics-drivers?field.series_filter=focal). Not sure why. Possible options are:
* Upgrate the image to ubuntu-22.04
* Use https://launchpad.net/~kisak/+archive/ubuntu/kisak-mesa (or some other mesa ppa) in place of oibaf

**Comment by S-Dafarra** [comment]
I tried the first in https://github.com/ami-iit/yarp-device-openxrheadset/tree/fix_ci
