### ISSUE TITLE
CI failure on Windows with conda dependencies due to glm

### ISSUE THREAD

**Issue by S-Dafarra** [ami-iit/yarp-device-openxrheadset#35]
Here the workflow failure: 
https://github.com/ami-iit/yarp-device-openxrheadset/actions/runs/4878414507/jobs/8706280938

The error is:
```
LINK : fatal error LNK1181: cannot open input file 'glm.lib' [D:\a\yarp-device-openxrheadset\yarp-device-openxrheadset\build\_deps\glfont-build\GLFont.vcxproj]
```

Apparently, there has been a recent update by @traversaro: https://github.com/conda-forge/glm-feedstock/pull/15

@traversaro any suggestion?

**Comment by traversaro** [comment]
Probably something is broken in glm CMake files upstream and the recipe did not have appropriate tests. This also broke the superbuild, I will check but I fear I only can this late afternoon, in the meanwhile a quick workaround is to install an older version of glm.

**Comment by traversaro** [comment]
By the way, Ubuntu 22.04 has the latest glm 0.9.9.8, but uses the `glm` target due to a local patch: https://sources.debian.org/patches/glm/0.9.9.8%2Bds-6/cmake-install-target.patch/ .

**Comment by traversaro** [comment]
I was wondering: but why conda-forge/Linux works? The point is this projects calls `find_package(GLM)` . As YCM is used, this calls https://github.com/robotology/ycm/blob/v0.15.1/find-modules/FindGLM.cmake, that inside calls `find_package(GLM CONFIG QUIET)` . This on Ubuntu does not find anything (and fallback to define a `glm` target), while in Windows it finds `glmConfig.cmake` as the filesystem is not case sensitive.

**Comment by traversaro** [comment]
Fixed by:
* https://github.com/robotology/ycm/pull/430
* https://github.com/robotology/ycm/pull/431
* https://github.com/conda-forge/ycm-cmake-modules-feedstock/pull/16
* https://github.com/robotology/robotology-superbuild/pull/1402

**Comment by S-Dafarra** [comment]
Thanks a lot! I guess I need to wait for ``ycm-cmake-modules`` ``v0.15.2`` to be available then. I tried to rerun it a few minutes ago, but it still downloads ``v0.15.1``: https://github.com/ami-iit/yarp-device-openxrheadset/actions/runs/4889262237/jobs/8731003883

**Comment by traversaro** [comment]
Fixed, see https://github.com/ami-iit/yarp-device-openxrheadset/actions/runs/4889262237/jobs/8735244636 .
